# Generated by Django 2.2.14 on 2020-07-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralPhysicalTraining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnasium',
            name='description',
            field=models.TextField(default='Физкультурный зал', verbose_name='Описание'),
        ),
    ]
