# Generated by Django 2.2.14 on 2020-07-24 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofp_teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата посещения'),
        ),
    ]
