# Generated by Django 2.2.14 on 2020-07-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofp_teachers', '0002_auto_20200725_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.CharField(default=-200, max_length=7, verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
